In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
iris_df = pd.read_csv('iris.csv') 
iris_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
iris_df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [6]:
iris_df.groupby("variety").variety.count()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [7]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
iris_df.corr()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000

petal.width and petal.lengthcorrelation must remove in seconde modelizer

In [9]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression, Perceptron 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.utils import shuffle

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
X, y = load_iris(return_X_y=True)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [31]:
gnb = GaussianNB()
perceptron_classifier = Perceptron()
lm_classifier = LogisticRegression(C=2)
knn_clf = KNeighborsClassifier(n_neighbors=3)


In [32]:
gnb_fit = gnb.fit(X_train, y_train)
perceptron_fit = perceptron_classifier.fit(X_train, y_train)
lm_fit = lm_classifier.fit(X_train, y_train)
knn_fit = knn_clf.fit(X_train, y_train)

In [33]:
gnb_pred = knn_fit.predict(X_test)
perceptron_pred = perceptron_fit.predict(X_test)
lm_pred = lm_fit.predict(X_test)
knn_pred = knn_fit.predict(X_test)

In [34]:
print("Logistic Regression")
print(classification_report(y_test, lm_pred))
print(classification_report(y_test, lm_pred))
confusion_matrix(y_test, lm_pred)

Logistic Regression
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75



array([[21,  0,  0],
       [ 0, 29,  1],
       [ 0,  4, 20]])

In [35]:
print("GaussianNB")
print(classification_report(y_test, gnb_pred))
print(classification_report(y_test, gnb_pred))
confusion_matrix(y_test, gnb_pred)

GaussianNB
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75



array([[21,  0,  0],
       [ 0, 29,  1],
       [ 0,  4, 20]])

In [36]:
print("Perceptron")
print(classification_report(y_test, perceptron_pred))
print(classification_report(y_test, perceptron_pred))
confusion_matrix(y_test, perceptron_pred)

Perceptron
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.40      0.57        30
           2       0.57      1.00      0.73        24

    accuracy                           0.76        75
   macro avg       0.86      0.80      0.77        75
weighted avg       0.86      0.76      0.74        75

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.40      0.57        30
           2       0.57      1.00      0.73        24

    accuracy                           0.76        75
   macro avg       0.86      0.80      0.77        75
weighted avg       0.86      0.76      0.74        75



array([[21,  0,  0],
       [ 0, 12, 18],
       [ 0,  0, 24]])

In [37]:
print("KNN")
print(classification_report(y_test, knn_pred))
print(classification_report(y_test, knn_pred))
confusion_matrix(y_test, knn_pred)

KNN
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      0.97      0.92        30
           2       0.95      0.83      0.89        24

    accuracy                           0.93        75
   macro avg       0.94      0.93      0.94        75
weighted avg       0.94      0.93      0.93        75



array([[21,  0,  0],
       [ 0, 29,  1],
       [ 0,  4, 20]])